### ISSUE TITLE
Unable to push profiles to the blackfire backend

### ISSUE THREAD

**Issue by JanDC** [blackfireio/node-continuous-profiling#2]
We're very excited to the prospect of node.js profiling in blackfire, but the agent is unable to push the gathered profiles to blackfire.
Trying this results in the following error: 'The continuous profiler feature is not enabled for your environment'

Are you able to support us in configuring our backend? There does not seem to be a continuous profiler option in the dashboard.

**Comment by SabriPlatform** [comment]
Hi @JanDC, I'm glad you're excited about node.js continuous profiling in Blackfire. It has yet to be released, which would explain why you are observing the error mentioned. Apologies about that! It's coming **very** soon. I'd be happy to follow up here once it's available. Hopefully, this helps.

**Comment by SabriPlatform** [comment]
Hi @JanDC, Following up on your question here. Continuous Profiling should now be available on Blackfire! Let us know if you're observing any issues or have any questions.

**Comment by JanDC** [comment]
Thank you for the heads up @SabriPlatform!
We'll be reviewing the node profiling soon and keep you appraised of any issues we may encounter
